name 'kitchen-docker-host'
maintainer 'Stefan Rusu'
maintainer_email 'saltwaterc@gmail.com'
license 'MIT'
description 'Installs/Configures kitchen-docker-host'
long_description 'Installs/Configures kitchen-docker-host'
version '0.1.2'
source_url 'https://git.io/vrMEH'
issues_url 'https://git.io/vrMEj'

depends 'yum-epel'
depends 'yum'
depends 'selinux'
