<% require_relative 'cinc_version' %>

driver:
  name: vagrant
  network:
  - ['private_network', {ip: '192.168.99.100'}]
  <% if File.exist? 'volumes.yml' %>
  synced_folders:
  <% YAML.load_file('volumes.yml').each do |volume| %>
  - ['<%= volume %>', '<%= volume %>']
  <% end %>
  <% end %>
  customize:
    name: kitchen-docker-host
    cpus: <%= ENV['VB_CPUS'] || 2 %>
    memory: <%= ENV['VB_MEM'] || 4096 %>
    vram: 8
    nictype1: virtio
    nictype2: virtio

provisioner:
  name: chef_zero
  product_name: cinc
  product_version: <%= CINC_VERSION %>

platforms:
- name: oracle8
  driver:
    box: generic/oracle8
    box_auto_update: true
    box_auto_prune: true

suites:
- name: kdh
  run_list:
  - recipe[kitchen-docker-host::test]
  - recipe[kitchen-docker-host::default]
