# <% require_relative 'cinc_version' %>

driver:
  name: vagrant
  network:
  - ['private_network', {ip: '192.168.99.100'}]
  customize:
    name: kitchen-docker-host
    cpus: <%= ENV['VB_CPUS'] || 2 %>
    memory: <%= ENV['VB_MEM'] || 4096 %>
    nictype1: virtio
    nictype2: virtio

provisioner:
  name: chef_zero
  product_name: cinc
  product_version: <%= CINC_VERSION %>

platforms:
- name: generic/oracle8

suites:
- name: kdh
  run_list:
  - recipe[kitchen-docker-host]
