# <% require_relative 'chef_version' %>

driver:
  name: vagrant
  network:
  - ['private_network', {ip: '192.168.99.100'}]
  customize:
    name: kitchen-docker-host
    cpus: <%= ENV['VB_CPUS'] || 4 %>
    memory: <%= ENV['VB_MEM'] || 4096 %>
    nictype1: virtio
    nictype2: virtio

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= CHEF_VERSION %>

platforms:
- name: centos-7.4

suites:
- name: kdh
  run_list:
  - recipe[kitchen-docker-host]
