Layout/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 40

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%i': '[]'
    '%w': '[]'

AllCops:
  NewCops: enable
  TargetChefVersion: 16.11
